In [1]:
import numpy as np

In [2]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])    

print("Vector 1:", v1)
print("Vector 2:", v2)

Vector 1: [1 2 3]
Vector 2: [4 5 6]


In [3]:
print(v1.shape)  

(3,)


In [ ]:
class Student:
    def __init__(self, name, age):
        self._name = name
        self.age = age
    @property
    def name(self):
        return f"Name: {self._name}"
s1 = Student("Alice", 20)
s1.name()

'Name: Alice'

In [ ]:
print(v2.ndim)

1


In [10]:
vec = np.array([1, 2, 3, 4, 5, 6])  # Create a 1D array (vector)
mat = vec.reshape(3, 2)  # Reshape to a 3x2 matrix
print("Vector:")
print(vec)
print("Matrix:")
print(mat)


Vector:
[1 2 3 4 5 6]
Matrix:
[[1 2]
 [3 4]
 [5 6]]


In [16]:
vec1 = np.array([1, 2, 3, 4])
print(vec1.shape[0])
mat1 = vec1.reshape((vec1.shape[0],1))  # Reshape to a 2x2 matrix
print(mat1)

4
[[1]
 [2]
 [3]
 [4]]


In [17]:
def array_reshape(arr, row = -1, col = -1):
    """
    Reshape a NumPy array to a new shape.

    Parameters:
    arr (np.ndarray): The input array to reshape.
    row, col (tuple): The desired shape for the output array.

    Returns:
    np.ndarray: The reshaped array.
    """
    try:
        arr = np.array(arr)
        return arr.reshape((row, col))
    except Exception as e:
        raise ValueError (f"Error reshaping array: {e}")    

vec2 = np.array([1, 2, 3, 4, 5, 6])
mat2 = array_reshape(vec2, 3, 2)
print(mat2)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.dtype

dtype('int64')

In [21]:
fmat = mat.astype(float)
print(fmat)
print   (fmat.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [24]:
mat[1,2]

np.int64(6)

In [26]:
mat[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
mat = np.array([[1, 2, 3],
                 [4, 5, 6],
                   [7, 8, 9],
                     [10, 11, 12]])

In [31]:
mat[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [32]:
mat= np.zeros((3,3))

In [33]:
mat[:]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
mat= np.full((3,3), 7)
mat[:]


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [35]:
mat = np.empty((3, 3))
mat[:]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
mat = np.arange(0, 361, 45)
mat

array([  0,  45,  90, 135, 180, 225, 270, 315, 360])

In [41]:
mat = np.linspace(0, 10, num = 10)
mat 

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [42]:
mat = np.identity(3)
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
import random 
np.random.random((3, 3))

array([[0.87439491, 0.76106033, 0.74576595],
       [0.81354202, 0.95897312, 0.56248659],
       [0.18952307, 0.04517365, 0.78929993]])