In [23]:
import numpy as np

In [2]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])    

print("Vector 1:", v1)
print("Vector 2:", v2)

Vector 1: [1 2 3]
Vector 2: [4 5 6]


In [3]:
print(v1.shape)  

(3,)


In [ ]:
class Student:
    def __init__(self, name, age):
        self._name = name
        self.age = age
    @property
    def name(self):
        return f"Name: {self._name}"
s1 = Student("Alice", 20)
s1.name()

'Name: Alice'

In [ ]:
print(v2.ndim)

1


In [10]:
vec = np.array([1, 2, 3, 4, 5, 6])  # Create a 1D array (vector)
mat = vec.reshape(3, 2)  # Reshape to a 3x2 matrix
print("Vector:")
print(vec)
print("Matrix:")
print(mat)


Vector:
[1 2 3 4 5 6]
Matrix:
[[1 2]
 [3 4]
 [5 6]]


In [16]:
vec1 = np.array([1, 2, 3, 4])
print(vec1.shape[0])
mat1 = vec1.reshape((vec1.shape[0],1))  # Reshape to a 2x2 matrix
print(mat1)

4
[[1]
 [2]
 [3]
 [4]]


In [17]:
def array_reshape(arr, row = -1, col = -1):
    """
    Reshape a NumPy array to a new shape.

    Parameters:
    arr (np.ndarray): The input array to reshape.
    row, col (tuple): The desired shape for the output array.

    Returns:
    np.ndarray: The reshaped array.
    """
    try:
        arr = np.array(arr)
        return arr.reshape((row, col))
    except Exception as e:
        raise ValueError (f"Error reshaping array: {e}")    

vec2 = np.array([1, 2, 3, 4, 5, 6])
mat2 = array_reshape(vec2, 3, 2)
print(mat2)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
mat.dtype

dtype('int64')

In [21]:
fmat = mat.astype(float)
print(fmat)
print   (fmat.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [24]:
mat[1,2]

np.int64(6)

In [26]:
mat[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
mat = np.array([[1, 2, 3],
                 [4, 5, 6],
                   [7, 8, 9],
                     [10, 11, 12]])

In [31]:
mat[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [32]:
mat= np.zeros((3,3))

In [33]:
mat[:]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
mat= np.full((3,3), 7)
mat[:]


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [35]:
mat = np.empty((3, 3))
mat[:]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
mat = np.arange(0, 361, 45)
mat

array([  0,  45,  90, 135, 180, 225, 270, 315, 360])

In [41]:
mat = np.linspace(0, 10, num = 10)
mat 

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [42]:
mat = np.identity(3)
mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
import random 
np.random.random((3, 3))

array([[0.59533495, 0.45759004, 0.70501262],
       [0.44619188, 0.81716027, 0.34955321],
       [0.98740221, 0.17890261, 0.67077232]])

In [19]:
class Student:
    def __init__(self, name, age):
        self._name = name
        self.age = age

    @property
    def name(self):
        return f"Name: {self._name}"

In [21]:
s1 = Student("Alicee", 20)
s1.name

'Name: Alicee'

In [25]:
vec = np.linspace(0, 10, num = 25)
mat = vec.reshape(5, 5)
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [30]:
np.random.randint(0,11,(5,5))

array([[8, 2, 3, 9, 3],
       [3, 3, 6, 2, 3],
       [3, 9, 6, 3, 0],
       [1, 5, 9, 3, 9],
       [9, 6, 9, 0, 1]], dtype=int32)

In [34]:
np.random.choice(["ahmed", "ali", "mohamed", "omar"],(5,5)) 

array([['omar', 'ali', 'ali', 'omar', 'mohamed'],
       ['ali', 'mohamed', 'mohamed', 'omar', 'mohamed'],
       ['omar', 'omar', 'ali', 'ali', 'omar'],
       ['omar', 'ahmed', 'ahmed', 'mohamed', 'mohamed'],
       ['ahmed', 'omar', 'ahmed', 'ahmed', 'omar']], dtype='<U7')

In [35]:
mat1 = np.ones((3, 3))
mat2 = np.zeros((3, 3))
mat1, mat2


(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]))

In [36]:
np.savez("matrices.npz", ones_mat=mat1, zeros_mat=mat2)

In [38]:
mat3= np.vstack((mat1, mat2))
mat3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.allclose(mat1, mat2, atol=1)

True

In [41]:
v = np.array([1, 2, 3,4,5,6,7,8,9,10])
condition = (v >= 5)  # Condition for numbers greater than or equal to 5
filtered_v = v[condition]  # Apply the condition to filter the array
print(filtered_v)  # Print the filtered array

[ 5  6  7  8  9 10]


In [42]:
c =2 
summation = v + c
multiplication = v * c
print("Summation:", summation)
print("Multiplication:", multiplication)

Summation: [ 3  4  5  6  7  8  9 10 11 12]
Multiplication: [ 2  4  6  8 10 12 14 16 18 20]


In [44]:
mat1 = np.array([[1, 2], [3, 4] ,[5, 6]])
v2 = np.array([0.6, 0.5])
mat3 = mat1 * v2
mat3

array([[0.6, 1. ],
       [1.8, 2. ],
       [3. , 3. ]])

In [ ]:
from scipy.sparse import csr_matrix,csc_matrix

ModuleNotFoundError: No module named 'scipy'