### Part 1 - Smart Array Factory

In [1]:
import numpy as np


def array_factory(mode, shape, value=None):
    """
    Create a NumPy array based on the specified mode.

    Args:
        mode (str): The type of array to create ("zeros", "ones", "full", "identity").
        shape (tuple | int): The shape of the array. For "identity", an int
            representing the size of the square matrix.
        value (int | float, optional): The fill value, required only when mode is "full".

    Returns:
        np.ndarray: The created NumPy array.

    Raises:
        ValueError: If mode is invalid, or if mode is "full" without a value.
    """
    if mode == "zeros":
        return np.zeros(shape)

    elif mode == "ones":
        return np.ones(shape)

    elif mode == "full":
        if value is None:
            raise ValueError("Company-grade Error: 'value' must be provided when mode='full'.")
        return np.full(shape, value)

    elif mode == "identity":
        # shape is expected to be an integer (size of the square matrix)
        n = shape if isinstance(shape, int) else shape[0]
        return np.eye(n)

    else:
        raise ValueError(f"Company-grade Error: Invalid mode '{mode}'. "
                          f"Choose from 'zeros', 'ones', 'full', 'identity'.")


# ---------------- Tests ----------------
print(array_factory("zeros", (2, 3)))
print()
print(array_factory("ones", (2, 3)))
print()
print(array_factory("full", (2, 3), 7))
print()
print(array_factory("identity", 3))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]]

[[7 7 7]
 [7 7 7]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Part 2 - Secure reshape and stack

In [2]:
def secure_reshape_and_stack(data1, data2, new_shape):
    """
    Reshape the first dataset and vertically stack it with the second dataset.

    Args:
        data1 (array-like): The first dataset to reshape.
        data2 (array-like): The second dataset.
        new_shape (tuple): The target shape for the first dataset.

    Returns:
        np.ndarray: The combined dataset after reshaping and stacking.

    Raises:
        ValueError: If the reshape or vertical stacking operation fails.
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)

        reshaped_arr1 = arr1.reshape(new_shape)
        result = np.vstack((reshaped_arr1, arr2))

        return result

    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")


# ---------------- Tests ----------------

# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6]

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [
    [7, 8, 9],
    [10, 11, 12]
]

final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)
print(final_report.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


### Part 3 - Apply Threshold   

In [3]:
def apply_threshold(arr, threshold, replacement_value=-1):
    """
    Replace elements greater than or equal to a threshold value.

    Args:
        arr (array-like): The input array.
        threshold (int | float): The threshold value.
        replacement_value (int | float, optional): The value used for replacement.

    Returns:
        np.ndarray: The modified NumPy array.
    """
    arr = np.array(arr)
    condition = arr >= threshold
    modified_arr = np.where(condition, replacement_value, arr)
    return modified_arr


# ---------------- Tests ----------------
v = np.array([1, 2, 3])
result = apply_threshold(v, 2, -20)
print(result)

arr2 = np.array([5, 10, 15, 20])
print(apply_threshold(arr2, 15))
print(apply_threshold(arr2, 10, 0))

[  1 -20 -20]
[ 5 10 -1 -1]
[5 0 0 0]
